# Generated by Django 4.1 on 2023-03-19 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('item_title', models.CharField(blank=True, default='', max_length=100)),
                ('item_body', models.TextField(blank=True, default='')),
                ('item_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('item_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
