# Generated by Django 4.1 on 2023-03-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_item_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempost',
            name='item_rating',
        ),
        migrations.DeleteModel(
            name='Item_Rating',
        ),
    ]
