# Generated by Django 4.1 on 2023-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='cibil_score',
            field=models.IntegerField(blank=True, default=300, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='anual_turnover',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
