# Generated by Django 4.1 on 2023-03-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_entrepreneurprofile_cibil_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='anual_turnover',
        ),
        migrations.AddField(
            model_name='startup',
            name='anual_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='cibil_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
