# Generated by Django 4.1 on 2023-03-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_startup_anual_turnover_startup_anual_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='anual_income',
            new_name='anual_turnover',
        ),
    ]
