# Generated by Django 4.1 on 2023-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='mentor_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
