# Generated by Django 4.1 on 2023-03-19 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_mentorprofile_mentor_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="end_date",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 3, 24), null=True
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="start_date",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 3, 24), null=True
            ),
        ),
        migrations.AddField(
            model_name="mentorship",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="end_date",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 3, 24), null=True
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="start_date",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 3, 24), null=True
            ),
        ),
    ]
